/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.veigadealmeida.trabalho.view.tab;

import br.edu.veigadealmeida.trabalho.Main;
import br.edu.veigadealmeida.trabalho.database.EmployeeDatabase;
import br.edu.veigadealmeida.trabalho.database.CustomerDatabase;
import br.edu.veigadealmeida.trabalho.manager.EmployeeManager;
import br.edu.veigadealmeida.trabalho.manager.CustomerManager;
import br.edu.veigadealmeida.trabalho.model.Customer;
import br.edu.veigadealmeida.trabalho.model.Employee;
import br.edu.veigadealmeida.trabalho.model.enums.Department;
import br.edu.veigadealmeida.trabalho.util.Util;
import br.edu.veigadealmeida.trabalho.view.customer.EditCustomerView;
import br.edu.veigadealmeida.trabalho.view.customer.AddCustomerView;
import br.edu.veigadealmeida.trabalho.view.customer.DeleteCustomerView;
import java.util.Enumeration;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Pedro
 */
public class CustomersTab extends javax.swing.JPanel {

    private static final CustomerDatabase partnerDatabase = new CustomerDatabase();
    private static final EmployeeDatabase employeeDatabase = new EmployeeDatabase();
    
    private final CustomerManager partnerManager;
    private final EmployeeManager employeeManager;
    
    private final Employee employee;
    
    private final String[] columns;
    
    private final Map<String, Main.Func2<Customer, String, Boolean>> columnFilters;
    
    /**
     * Creates new form EmployeesDisplay
     */
    public CustomersTab(Employee employee) {
        initComponents();
        partnerManager = new CustomerManager(partnerDatabase);
        employeeManager = new EmployeeManager(employeeDatabase);
        columns = new String[]{"Nome", "Documento", "Endereço", "Telefone", "E-Mail", "Representante", "Responsável", "Login", "Senha"};
        table.setModel(new DefaultTableModel(partnerManager.toDataArray(), columns));
        Enumeration<TableColumn> tableColumns = table.getColumnModel().getColumns();
        while(tableColumns.hasMoreElements())
            tableColumns.nextElement().setMinWidth(150);
        table.setDefaultEditor(Object.class, null);
        filterSelector.setModel(new DefaultComboBoxModel<>(columns));
        columnFilters = Map.of(
                "Nome", (p, s) -> p.getName().toLowerCase().startsWith(s.toLowerCase()),
                "Documento", (p, s) -> p.getDocument().startsWith(s),
                "Endereço", (p, s) -> p.getAddress().toLowerCase().startsWith(s.toLowerCase()),
                "Telefone", (p, s) -> p.getPhone().startsWith(s),
                "E-Mail", (p, s) -> p.getEmail().toLowerCase().startsWith(s.toLowerCase()),
                "Representante", (p, s) -> p.getRepresentative().toLowerCase().startsWith(s.toLowerCase()),
                "Responsável", (p, s) -> p.getResponsibleEmployee().toLowerCase().startsWith(s.toLowerCase()),
                "Login", (p, s) -> p.getLogin().equals(s),
                "Senha", (p, s) -> p.getPassword().equals(s)
        );
        this.employee = employee;
        if(employee.getDepartment().ordinal() < Department.PMO.ordinal()) {
            addButton.setEnabled(false);
            editButton.setEnabled(false);
            deleteButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBar = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        filterSelector = new javax.swing.JComboBox<>();
        queryField = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();
        resetFilterButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        footer = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        searchBar.setPreferredSize(new java.awt.Dimension(877, 50));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Clientes");

        filterSelector.setBorder(null);
        filterSelector.setPreferredSize(new java.awt.Dimension(72, 25));

        queryField.setToolTipText("Pesquisar");
        queryField.setPreferredSize(new java.awt.Dimension(64, 25));
        queryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeQuery(evt);
            }
        });

        filterButton.setText("Filtrar");
        filterButton.setToolTipText("Clique para filtrar");
        filterButton.setPreferredSize(new java.awt.Dimension(75, 25));
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeQuery(evt);
            }
        });

        resetFilterButton.setText("Limpar Filtro");
        resetFilterButton.setToolTipText("Clique para limpar o filtro");
        resetFilterButton.setPreferredSize(new java.awt.Dimension(125, 25));
        resetFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFilter(evt);
            }
        });

        javax.swing.GroupLayout searchBarLayout = new javax.swing.GroupLayout(searchBar);
        searchBar.setLayout(searchBarLayout);
        searchBarLayout.setHorizontalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(filterSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchBarLayout.setVerticalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filterSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(queryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleLabel))
                .addContainerGap())
        );

        add(searchBar);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPane.setViewportView(table);

        add(scrollPane);

        addButton.setText("Cadastrar Cliente");
        addButton.setPreferredSize(new java.awt.Dimension(175, 23));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeClick(evt);
            }
        });

        deleteButton.setText("Remover Cliente");
        deleteButton.setPreferredSize(new java.awt.Dimension(175, 23));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonClick(evt);
            }
        });

        editButton.setText("Alterar Cliente");
        editButton.setPreferredSize(new java.awt.Dimension(175, 23));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonClick(evt);
            }
        });

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(footer);
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeClick
        // TODO add your handling code here:
        if(employeeManager.getAllTypes().isEmpty()) {
            Util.showError(this, "Nenhum funcionário cadastrado para ser responsável pelo associado.");
            return;
        }
        new AddCustomerView(employee, partnerManager, employeeManager).setVisible(true);
    }//GEN-LAST:event_addEmployeeClick

    
    private void deleteButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonClick
        // TODO add your handling code here:
        if(partnerManager.getAllTypes().isEmpty()) {
            Util.showError(this, "Nenhum associado cadastrado no sistema.");
            return;
        }
        new DeleteCustomerView(partnerManager).setVisible(true);
    }//GEN-LAST:event_deleteButtonClick

    private void editButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonClick
        // TODO add your handling code here:
        if(table.getSelectedRowCount() != 1) {
            Util.showError(this, "Selecione 1 associado para editar.");
            return;
        }
        String name = table.getValueAt(table.getSelectedRow(), 0).toString();
        Customer partner = partnerManager.getType(name);
        if(partner == null) {
            Util.showError(this, "Não foi possível editar o associado.");
            return;
        }
        new EditCustomerView(partnerManager, employeeManager, partner).setVisible(true);
    }//GEN-LAST:event_editButtonClick

    private void filterTable() {
        Main.Func2<Customer, String, Boolean> func = columnFilters.get(filterSelector.getItemAt(filterSelector.getSelectedIndex()));
        if(func == null) return;
        String query = queryField.getText();
        table.setModel(new DefaultTableModel(partnerManager.toDataArray(partnerManager.getAllTypes().stream().filter(partner -> func.make(partner, query)).toList()), columns));
        revalidate();
    }
    
    private void typeQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeQuery
        // TODO add your handling code here:
        filterTable();
    }//GEN-LAST:event_typeQuery

    private void resetFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFilter
        // TODO add your handling code here:
        queryField.setText("");
        filterTable();
    }//GEN-LAST:event_resetFilter


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton filterButton;
    private javax.swing.JComboBox<String> filterSelector;
    private javax.swing.JPanel footer;
    private javax.swing.JTextField queryField;
    private javax.swing.JButton resetFilterButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel searchBar;
    private javax.swing.JTable table;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
