/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.veigadealmeida.trabalho.view;

import br.edu.veigadealmeida.trabalho.database.CustomerDatabase;
import br.edu.veigadealmeida.trabalho.database.EmployeeDatabase;
import br.edu.veigadealmeida.trabalho.model.Customer;
import br.edu.veigadealmeida.trabalho.model.Employee;
import br.edu.veigadealmeida.trabalho.model.enums.Department;
import br.edu.veigadealmeida.trabalho.util.Util;

/**
 *
 * @author Pedro
 */
public class LoginView extends javax.swing.JFrame {

    private final EmployeeDatabase employeeDatabase;
    private final CustomerDatabase customerDatabase;
    
    /**
     * Creates new form LoginView
     */
    public LoginView() { //Iniciando tela de login
        initComponents(); //Código gerado
        setLocationRelativeTo(null); //Centralizar a tela
        employeeDatabase = new EmployeeDatabase(); //Conectar ao banco de dados de funcionários para autenticação
        customerDatabase = new CustomerDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePane = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        formPane = new javax.swing.JPanel();
        loginlabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginPanel = new javax.swing.JPanel();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        titlePane.setMaximumSize(new java.awt.Dimension(300, 100));
        titlePane.setMinimumSize(new java.awt.Dimension(300, 100));
        titlePane.setPreferredSize(new java.awt.Dimension(300, 100));
        titlePane.setLayout(new java.awt.GridLayout(2, 0, 0, -25));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Tech Nest");
        titlePane.add(title);

        subTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle.setText("Autentique-se para entrar no sistema:");
        titlePane.add(subTitle);

        getContentPane().add(titlePane);

        formPane.setMaximumSize(new java.awt.Dimension(200, 150));
        formPane.setMinimumSize(new java.awt.Dimension(200, 100));
        formPane.setPreferredSize(new java.awt.Dimension(200, 100));
        formPane.setLayout(new java.awt.GridLayout(5, 0));

        loginlabel.setText("Login");
        formPane.add(loginlabel);
        formPane.add(loginField);

        passwordLabel.setText("Senha");
        formPane.add(passwordLabel);
        formPane.add(passwordField);

        getContentPane().add(formPane);

        loginPanel.setMaximumSize(new java.awt.Dimension(125, 45));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoginClick(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(loginPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onLoginClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLoginClick
        // TODO add your handling code here:
        String login = loginField.getText(), password = new String(passwordField.getPassword()); //Conseguindo os valores informados pelo usuário através dos campos
        if(login.isEmpty() && password.isEmpty()) {
            dispose();
            new AdminAppView(new Employee("Admin", "-/-", "-/-", "-/-", "admin@technest.com", "admin", "admin", Department.ADMIN)).setVisible(true);
            return;
        }
        Employee employee = employeeDatabase.findByLoginAndPassword(login, password); //Buscar funcionário no banco que tenha login e senha equivalentes aos fornecidos
        Customer customer = null;
        if(employee == null) { //Nesse caso, login é inválido ou senha é incorreta
            customer = customerDatabase.findByLoginAndPassword(login, password);
            if(customer == null) {
                Util.showError(this, "Usuário ou senha inválidos."); //Então, mostrar erro
                return; //Então, parar aqui
            }
        }
        //Nesse caso, usuário encontrado e autenticado
        dispose(); //Fechar tela de login
        if(customer != null) new CustomerAppView(customer).setVisible(true);
        else if(employee.getDepartment().equals(Department.ADMIN))
            new AdminAppView(employee).setVisible(true); //Abrir tela principal passando o funcionário que logou
        else if(employee.getDepartment().equals(Department.PMO)) new PMPAppView(employee).setVisible(true);
        else new EmployeeAppView(employee).setVisible(true);
    }//GEN-LAST:event_onLoginClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formPane;
    private javax.swing.JButton login;
    private javax.swing.JTextField loginField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePane;
    // End of variables declaration//GEN-END:variables
}
