/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.veigadealmeida.trabalho.view.task;

import br.edu.veigadealmeida.trabalho.view.employee.*;
import br.edu.veigadealmeida.trabalho.manager.EmployeeManager;
import br.edu.veigadealmeida.trabalho.manager.TaskManager;
import br.edu.veigadealmeida.trabalho.model.Employee;
import br.edu.veigadealmeida.trabalho.model.Task;
import br.edu.veigadealmeida.trabalho.view.AdminAppView;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Pedro
 */
public class DeleteTaskView extends javax.swing.JFrame {
    
    private final TaskManager taskManager;
    
    /**
     * Creates new form DeleteEmployeeView
     * @param taskManager
     */
    public DeleteTaskView(TaskManager taskManager) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.taskManager = taskManager;
        taskSelector.setModel(new DefaultComboBoxModel<>(taskManager.getAllTypes().stream().map(Task::getId).toList().toArray(new String[0])));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        employeeLabel = new javax.swing.JLabel();
        taskSelector = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setPreferredSize(new java.awt.Dimension(250, 160));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Deletar Tarefa");
        panel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, -1));

        employeeLabel.setText("Tarefa");
        panel.add(employeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        panel.add(taskSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, -1));

        deleteButton.setText("Deletar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClick(evt);
            }
        });
        panel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClick
        // TODO add your handling code here:
        Task task = taskManager.getAllTypes().stream().filter(t -> t.getId().equals(taskSelector.getItemAt(taskSelector.getSelectedIndex()))).findFirst().orElse(null);
        if(task == null) return;
        taskManager.getAllTypes().remove(task);
        taskManager.getDatabase().save(taskManager.getAllTypes());
        dispose();
        AdminAppView.requestUpdateVisualization();
    }//GEN-LAST:event_deleteClick

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> taskSelector;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
