/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.veigadealmeida.trabalho.view.customer;

import br.edu.veigadealmeida.trabalho.manager.CustomerManager;
import br.edu.veigadealmeida.trabalho.model.Customer;
import br.edu.veigadealmeida.trabalho.util.Util;
import br.edu.veigadealmeida.trabalho.view.AdminAppView;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Pedro
 */
public class DeleteCustomerView extends javax.swing.JFrame {

    private final CustomerManager manager;
    
    /**
     * Creates new form DeleteEmployeeView
     * @param manager
     */
    public DeleteCustomerView(CustomerManager manager) {
        initComponents();
        setLocationRelativeTo(null);
        this.manager = manager;
        partnerSelector.setModel(new DefaultComboBoxModel<>(manager.getAllTypes().stream().map(Customer::getName).toList().toArray(new String[0])));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        partnerLabel = new javax.swing.JLabel();
        partnerSelector = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setPreferredSize(new java.awt.Dimension(250, 160));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Deletar Associado");
        panel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, -1));

        partnerLabel.setText("Associado");
        panel.add(partnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        panel.add(partnerSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, -1));

        deleteButton.setText("Deletar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClick(evt);
            }
        });
        panel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClick
        // TODO add your handling code here:
        Customer partner = manager.getType(partnerSelector.getItemAt(partnerSelector.getSelectedIndex()));
        if(partner == null) {
            Util.showError(this, "Associado não encontrado.");
            return;
        }
        manager.getAllTypes().remove(partner);
        manager.getDatabase().save(manager.getAllTypes());
        dispose();
        AdminAppView.requestUpdateVisualization();
    }//GEN-LAST:event_deleteClick

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel partnerLabel;
    private javax.swing.JComboBox<String> partnerSelector;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
