/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.veigadealmeida.trabalho.view.project;

import br.edu.veigadealmeida.trabalho.model.Project;

/**
 *
 * @author Pedro
 */
public class ProjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProjectPanel
     */
    /**
     * Essa classe representa um Componente, que é um pedaço de tela que pode ser preenchido com
     * dados de um determinado objeto fornecido, nesse caso, trata-se de um retângulo avulso que
     * mostra as informações do
     * @param project
     * recebido no construtor da classe
     */
    public ProjectPanel(Project project) {
        initComponents();
        this.name.setText(project.getName());
        this.description.setText(project.getDescription());
        this.partner.setText(project.getPartner());
        this.responsibleEmployee.setText(project.getResponsibleEmployee());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        partnerLabel = new javax.swing.JLabel();
        partner = new javax.swing.JLabel();
        responsibleEmployeeLabel = new javax.swing.JLabel();
        responsibleEmployee = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        details = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        description = new javax.swing.JTextPane();

        setMinimumSize(new java.awt.Dimension(835, 125));
        setPreferredSize(new java.awt.Dimension(835, 125));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("Project Name");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        partnerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        partnerLabel.setText("Partner");
        add(partnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        partner.setText("Partner name");
        add(partner, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        responsibleEmployeeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        responsibleEmployeeLabel.setText("Responsible Employee");
        add(responsibleEmployeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        responsibleEmployee.setText("Responsible employee name");
        add(responsibleEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statusLabel.setText("Status");
        add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        status.setText("Project status");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        details.setText("Detalhes");
        add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        description.setEditable(false);
        description.setText("Project description");
        scrollPane.setViewportView(description);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 280, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane description;
    private javax.swing.JButton details;
    private javax.swing.JLabel name;
    private javax.swing.JLabel partner;
    private javax.swing.JLabel partnerLabel;
    private javax.swing.JLabel responsibleEmployee;
    private javax.swing.JLabel responsibleEmployeeLabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel status;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
